# Generated by Django 5.1.3 on 2025-01-27 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background_remover', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
    ]
