# Generated by Django 5.1.6 on 2025-06-14 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Text2ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("negative_prompt", models.TextField()),
                ("seed", models.IntegerField(default=0)),
                ("randomize_seed", models.BooleanField(default=True)),
                ("width", models.IntegerField(default=1024)),
                ("height", models.IntegerField(default=768)),
                ("guidance_scale", models.FloatField()),
                ("num_inference_steps", models.IntegerField(default=40)),
                ("num_images", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Text-to-Image Request",
                "verbose_name_plural": "Text-to-Image Requests",
                "db_table": "text2image_requests",
            },
        ),
        migrations.CreateModel(
            name="GeneratedImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="text2image/")),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "text2image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ai_text_to_image_generator.text2imagemodel",
                    ),
                ),
            ],
        ),
    ]
