# Generated by Django 5.1.2 on 2025-03-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StyleTransferImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_image", models.ImageField(upload_to="uploads/")),
                ("style_image", models.ImageField(upload_to="uploads/")),
                (
                    "result_image",
                    models.ImageField(blank=True, null=True, upload_to="results/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
