name: Restrict Pull Requests

on:
  pull_request:
    branches:
      - Frontend
      - testing
      - main

jobs:
  restrict-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Check Pull Request Source and Target
        env:
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
          AUTHOR: ${{ github.actor }}
        run: |
          if [[ "$TARGET_BRANCH" == "Frontend" && "$AUTHOR" != "SoapMac" ]]; then
            echo "Only user 'SoapMac' can create pull requests to 'Frontend'."
            exit 1
          elif [[ "$TARGET_BRANCH" == "testing" && "$SOURCE_BRANCH" != "Frontend" && "$SOURCE_BRANCH" != "Backend" ]]; then
            echo "Pull requests to 'testing' can only come from 'Frontend' or 'Backend'."
            exit 1
          elif [[ "$TARGET_BRANCH" == "main" && "$SOURCE_BRANCH" != "testing" ]]; then
            echo "Pull requests to 'main' can only come from 'testing'."
            exit 1
          else
            echo "Pull request allowed."
          fi
